// Generated by CoffeeScript 1.6.2
/*
Module dependencies.
*/


(function() {
  var app, express, http, path;

  express = require("express");

  http = require("http");

  path = require("path");

  app = express();

  app.configure(function() {
    app.set("port", process.env.PORT || 3011);
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.favicon());
    app.use(express.logger("dev"));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express["static"](path.join(__dirname, "public")));
    return app.use(express["static"](path.join(__dirname, "components")));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler());
  });

  app.get("/", function(req, res) {
    return res.render("index");
  });

  app.get("/links", function(req, res) {
    return res.render("links");
  });

  app.get("/privacy-policy/", function(req, res) {
    return res.render("privacy-policy");
  });

  app.get("/portfolio/", function(req, res) {
    return res.redirect("/");
  });

  app.get("/flight/?", function(req, res) {
    return res.render("flight");
  });

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
